version: '3.5' # specify docker-compose version

# Define the services/containers to be run
services:
  client:
    build: ./Front/Client
    ports:
      - "80:4200"
    volumes: 
        - ./Front/Client:/usr/src/app
        - /usr/src/app/node_modules
    networks:
       - webnet
  cms:
    build: ./Front/CMS
    ports:
      - "2000:2000"
    volumes: 
        - ./Front/CMS:/usr/src/app
        - /usr/src/app/node_modules
    networks:
        - webnet
  backend:
    build: ./Back
    ports:
      - "3000:3000"
    volumes: 
        - ./Back:/usr/src/app
        - /usr/src/app/node_modules
    networks:
        - webnet
    command: npm run start:dev
    environment:
      DATABASE_URL: db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ibanez123
      POSTGRES_USER: postgres
      POSTGRES_DB: socialnetwork
    ports:
    - 5432:5432
    volumes:
    - ./Back/pgdata:/var/lib/postgresql/data
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata:
